# Generated by Django 4.1.3 on 2023-02-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_profileclient_document_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileclient',
            name='document_number',
            field=models.CharField(default='2023-02-15 15:30:14.006045', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='profileclient',
            name='document_type',
            field=models.CharField(choices=[('CC', 'CEDULA DE CIUDADANIA'), ('CE', 'CEDULA DE EXTRANJERIA'), ('PA', 'PASAPORTE'), ('TI', 'TARJETA DE IDENTIDAD'), ('IT', 'IDENTIFICACION TRIBUTARIA'), ('IP', 'IDENTIFICACION PERSONAL')], default='CC', max_length=3),
        ),
    ]
