# Generated by Django 4.1.3 on 2023-06-06 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_profileclient_document_number'),
        ('booking', '0003_bookingspa_end_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingspa',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.profileclient'),
        ),
    ]
